version: '3.4'

services:
  frontend:
    build:
      context: ./Car-Booking-App
    ports:
      - "4200:80"

  backend:
    build:
      context: ./CarBookingAPI
    ports:
      - "7080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
